ALTER TABLE clientes
ADD COLUMN dt_nasc date;

ALTER TABLE clientes
DROP COLUMN dt_nasc;

ALTER TABLE clientes
ALTER COLUMN bairro TYPE VARCHAR(50);

ALTER TABLE clientes
ALTER COLUMN bairro TYPE VARCHAR(40);

ALTER TABLE clientes
RENAME COLUMN identidade TO rg;

ALTER TABLE clientes
RENAME TO cliente;

--ALTER TABLE / ADD CONSTRAINT
ALTER TABLE funcionarios
ADD CONSTRAINT cpf_unico UNIQUE(cpf);

--REMOVENDO RESTRIÇÃO
ALTER TABLE funcionarios
DROP CONSTRAINT cpf_unico;

--INSERINDO UM VALOR PADRÃO
ALTER TABLE cliente
ALTER COLUMN  uf SET DEFAULT 'PI';

--EXCLUINDO UM VALOR PADRÃO
ALTER TABLE cliente
ALTER COLUMN uf DROP DEFAULT;

-- ADICIONANDO RESTRIÇÃO DE NOT NULL // SE UM DOS REGISTROS TIVER NULL, ENTÃO O COMANDO NÃO SERA RODADO.
ALTER TABLE cliente
ALTER COLUMN telefone SET NOT NULL;

--EXCLUINDO RESTRIÇÃO DO NOT NULL.
ALTER TABLE cliente
ALTER COLUMN telefone DROP NOT NULL;