SELECT * FROM cliente

INSERT INTO cliente
VALUES('andre@gmail.com', 1, 'andre santos', '17/07/2000', 32185334, 994924740, 77829393, 99091872)

INSERT INTO cliente
VALUES('kelso@hotmail.com', 1, 'kelso matos', '12/10/1992', 32185354, 994924790, 88829393, 78091872)

INSERT INTO cliente
VALUES('crisborgez@gmail.com', 1, 'Cris asia', '11/08/1967', 32187817, 994950998, 11989283, 67621234)


INSERT INTO cliente
VALUES('costa@gmail.com', 1, 'Costinha', '13/09/1978', null, 99497828, 871231283, 88921234)

SELECT * FROM cliente


SELECT data_nascimento, fone_residencial, cpf FROM cliente;

SELECT DISTINCT nome FROM cliente

SELECT * FROM cliente
WHERE data_nascimento = '11/10/1993'
AND senha = '15461546'

SELECT nome FROM cliente
WHERE fone_residencial IS NOT NULL

SELECT nome FROM cliente
WHERE fone_residencial IS NULL

SELECT * FROM cliente
WHERE nome IN ('Costinha','Cris asia')

SELECT * FROM cliente
WHERE nome = 'Costinha' OR nome = 'Cris asia'

SELECT * FROM cliente
WHERE data_nascimento BETWEEN '11/10/1993' AND '17/07/2000'

SELECT * FROM cliente
WHERE nome LIKE 'C%' /*PEDI PRA SELECIONAR O CAMPO NOME ONDE A PRIMEIRA LETRA É 'C'*/

SELECT * FROM cliente
WHERE nome LIKE '%a' /*PEDI PRA SELECIONAR O CAMPO NOME ONDE A ÚLTIMA LETRA TERMINA COM 'a'*/

SELECT * FROM cliente
WHERE nome LIKE '__e%' /*PEDI PRA SELECIONAR O CAMPO NOME ONDE A 3º LETRA COMEÇA COM 'e'*/

SELECT * FROM cliente
WHERE nome SIMILAR TO '[KL]%' /*PEDI PRA SELECIONAR O CAMPO ONDE A PRIMEIRA LETRA PODE COMEÇAR COM 'K' OU 'L', O RESTO NAO IMPORTA*/

SELECT * FROM cliente
WHERE nome SIMILAR TO '[^KL]%' /*PEDI PRA SELECIONAR O CAMPO ONDE O NOME SÓ NÃO PODE COMEÇAR COM 'K' OU COM 'L'*/

SELECT * FROM cliente
ORDER BY nome DESC   /*ORDENO OS NOMES DE FORMA DECRESCENTE(DO MENOR PARA O MAIOR)*/

SELECT * FROM cliente
LIMIT 2 /*LIMITO O RETORNO DA TABELA CLIENTE EM APENAS 2 LINHAS*/

SELECT * FROM cliente
ORDER BY data_nascimento
LIMIT 1 /*DESSA FORMA AQUI EU RETORNEI A DATA DE NASCIMENTO ORDENADA(MENOR PARA MAIOR/PADRÃO), E O COMO O 'LIMIT 1' SEI QUEM É O MAIS VELHO*/

SELECT * FROM cliente
ORDER BY data_nascimento
LIMIT 1 OFFSET 1 /*AQUI EU DIGO PRA ELE ME RETORNAR A data_nascimento COM LIMIT 1, E O 'OFFSET 1' DIZ QUE
PRA ELE ME RETORNAR 1 TUPLA DEPOIS DA DEFINIDA PELO LIMIT 1*/






